### ISSUE TITLE
Tier 6 landuse  & pois still shows up at zoom 9 (should be 12 or 13 min)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1079]
* **What did you see?** Schools everywhere! place_of_worship everywhere!
* **What did you expect to see?** Only big schools first, then medium schools, then larger schools.
* **What map location are you having problems with?** All over SF Bay Area.
* **Screenshot?** See below:

Here's the Bubble Wrap code snippet that makes it more sane:

```
        tier6:
            filter:
                all:
                    - kind: [garden, allotments, parking, pedestrian, common, pitch, place_of_worship, playground, school]
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 }, area: true }
```

10/37.3512/-121.9706
11/37.3512/-121.9706
12/37.3512/-121.9706

<img width="386" alt="screen shot 2016-09-22 at 09 23 56" src="https://cloud.githubusercontent.com/assets/853051/18756887/6f6593e2-80a6-11e6-8d18-136297840e30.png">
<img width="725" alt="screen shot 2016-09-22 at 09 23 51" src="https://cloud.githubusercontent.com/assets/853051/18756888/6f7da266-80a6-11e6-9ddf-a11a592aaff4.png">
<img width="879" alt="screen shot 2016-09-22 at 09 23 45" src="https://cloud.githubusercontent.com/assets/853051/18756889/6f7f1e0c-80a6-11e6-9bf5-95400b97ccc6.png">
