### ISSUE TITLE
POI labels for parks show up too late / too early

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1081]
- **What did you see?** Adirondack Park in NY state label only shows up at zoom 9, other minor parks show up way too early.
- **What did you expect to see?** Adarondak should show up based on it's huge size more like 6. Other should be pushed back a few zooms.
- **What map location are you having problems with?** New York state, San Francisco.
- **Screenshot?** 

7/43.804/-74.435
<img width="352" alt="screen shot 2016-09-22 at 09 33 24" src="https://cloud.githubusercontent.com/assets/853051/18757238/ded7733e-80a7-11e6-9a4c-af40cc5b72dc.png">

10/37.6180/-122.1185
<img width="989" alt="screen shot 2016-09-22 at 09 37 44" src="https://cloud.githubusercontent.com/assets/853051/18757317/42d4299a-80a8-11e6-8142-3c8da55880b6.png">

Adding filters back on the labels like so seems to fix it (let's refine):

```
landuse-labels-green-areas-not-national-park:
                filter:
                    all:
                        - area: true
                        - $geometry: point
                        - kind: [park, conservation, protected_area, nature_reserve, forest, grass]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [5],    area: { min: 10000000000 } }
                        - { $zoom: [6,7],  area: { min: 5000000000 } }
                        - { $zoom: [8],    area: { min: 1000000000 } }
                        - { $zoom: [9],    area: { min: 100000000 } }
                        - { $zoom: [10],   area: { min: 50000000 } }
                        - { $zoom: [11],   area: { min: 25000000 } }
                        - { $zoom: [12],   area: { min: 5000000 } }
                        - { $zoom: [13],   area: { min: 200000 } }
                        - { $zoom: [14],   area: { min: 50000 } }
                        - { $zoom: [15],   area: { min: 10000 } }
                        - { $zoom: [16],   area: { min: 1000 } }
                        - { $zoom: { min: 17 }, area: true }
```
