### ISSUE TITLE
Refine poi min_zoom for place_of_worship and other features

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1085]
Following up from #1084 which noted a funky min_zoom for Grace Cathedral in SF... 

I suspect:
- significant `place_of_worship` features don't always show up early enough, like Grace Cathedral in SF. I suspect we need to measure areas from landuse polygons differently than areas from buildings to get it more back to the earlier behavior. The current zooms feel good for landuse based areas (cap at zoom 12), but the buildings probably need to reset to be closer to the earlier v0.10 behavior, but with a cap at zoom 14.

<img width="560" alt="screen shot 2016-09-22 at 23 00 12" src="https://cloud.githubusercontent.com/assets/853051/18775695/65e85f62-8118-11e6-8cf7-1958085012b7.png">

<img width="395" alt="screen shot 2016-09-22 at 22 59 49" src="https://cloud.githubusercontent.com/assets/853051/18775696/66639bf0-8118-11e6-8c55-5b2a36ad3cec.png">

<img width="691" alt="screen shot 2016-09-22 at 22 59 38" src="https://cloud.githubusercontent.com/assets/853051/18775698/66690fae-8118-11e6-8081-c5d016c8a69e.png">

<img width="425" alt="screen shot 2016-09-22 at 22 58 34" src="https://cloud.githubusercontent.com/assets/853051/18775697/66666308-8118-11e6-8f89-8d37b9686658.png">
- `garden` zooms just seem way off with far too many at mid-zooms, I suspect because of the 12 in the filter:
  
  `min_zoom: { min: [ 12, { max: [ { lit: zoom }, { lit: *tier6_min_zoom } ] }, 16 ] }`
  
  versus something in the more dominant pattern:
  
  `min_zoom: { min: [ { max: [ 12, { lit: zoom }, { lit: *tier6_min_zoom } ] }, 16 ] }`
  
  In the Bubble Wrap stylesheet I'm using this to throttle `garden` features back:
  
  ```
  garden-area-early:
                   filter:
                       all:
                           - kind: [garden, allotments]
                       any:
                           # limit show smaller landuse areas to higher zooms
                           - { $zoom: [12], area: { max: 500000 } }
                           - { $zoom: [13], area: { max: 100000 } }
                           - { $zoom: [14], area: { max: 10000 } }
                           - { $zoom: [15], area: { max: 5000 } }
                   draw:
                       icons:
                           visible: false
  ```

<img width="468" alt="screen shot 2016-09-22 at 22 49 53" src="https://cloud.githubusercontent.com/assets/853051/18775624/d9e6272e-8117-11e6-9dd5-669c8aaa687e.png">
<img width="377" alt="screen shot 2016-09-22 at 22 49 21" src="https://cloud.githubusercontent.com/assets/853051/18775626/d9ff9826-8117-11e6-92b2-c3355e626b98.png">
<img width="453" alt="screen shot 2016-09-22 at 22 48 58" src="https://cloud.githubusercontent.com/assets/853051/18775627/da01044a-8117-11e6-9da5-a54ebed62e00.png">
<img width="886" alt="screen shot 2016-09-22 at 22 48 47" src="https://cloud.githubusercontent.com/assets/853051/18775625/d9ff09c4-8117-11e6-9f8e-9b0063cfbb1b.png">
