### ISSUE TITLE
Customized bike map mode sort_ranks

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1248]
* **What did you see?**

The bike map overlay could use some custom `sort_rank` values.

Related, once we add server-side priorities on pois in https://github.com/tilezen/vector-datasource/issues/988 we also change the priorities in bike map mode like in https://github.com/tangrams/walkabout-style/blob/gh-pages/layers/bike-interlay.yaml#L141-L168.

Below is example where if a road is bike related it should sort above the not bike related road's fill. See Morgan Dr and Rainey Dr and the line mitering isn't ideal (the orange lines should be on top of the white lines). 

We also modify the orders a bit for some zooms to improve the casing joins in several places, like:

https://github.com/tangrams/walkabout-style/blob/gh-pages/layers/bike-interlay.yaml#L1008

```
        bike_tier1_on_road_greenway:
            filter: global.greenway_on_road_filter
            early_order:
                filter: { $zoom: [12,13] }
                draw:
                    lines:
                        order: function() { return feature.sort_rank + 10; }
```

* **What map location are you having problems with?** 

Chicago:
https://tangrams.github.io/walkabout-style/#19/41.79324/-87.61045

* **Screenshot?**

![screen shot 2017-05-12 at 13 46 10](https://cloud.githubusercontent.com/assets/853051/26016584/77ad071c-371a-11e7-834a-f28c1e376738.png)
![screen shot 2017-05-12 at 13 46 00](https://cloud.githubusercontent.com/assets/853051/26016585/77b38be6-371a-11e7-9480-16bf7d319c5b.png)
