### ISSUE TITLE
add documentation for queries.yaml config

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1269]
Per support request in Gitter chat, we should document the hows, whats, and why's of the queries.yaml.

https://gitter.im/tilezen/tilezen-chat?at=59385e37f31c8ced0c1329e3

/cc @pnorman

**Comment by nvkelso** [comment]
Some of my notes in Gitter:

the `all:` block is a special synthetic layer target

then the `layers:` block sets out the actual layers.

`template: landuse.jinja2` says what file in an assumed path the SQL selection is specified – rob is simplifying that now though

most layers start at zero, but some like landuse don't: `start_zoom: 4`. in that case because landuse is expensive at low zooms we're saying don't even execute the SQL selection until zoom 4

`geometry_types: [Polygon, MultiPolygon, LineString, MultiLineString]` lists out valid geom types – but there is some magic elsewhere for that – if you're just dealing with OSM and Natural Earth data you don't need to worry about the magic, but not listing a geom type there will exclude it from export in tiles

for a few layers we trust the geom in the database is already good and we don't want to oversimply it so for roads you'll see: simplify_start: 8

then the `transform:` section lists which python transforms to apply to the layer's features once they're queried from the DB

historically we didn't clip buildings at all, and now we clip to 3 tiles worth, see `clip_factor: 3.0`

`area-inclusion-threshold: 1` I think just means things need to be at least a pixel big to export

the `post_process:` block says which vectordatasource python transform to apply to which layers with which options

that's also how we add in additional properties using CSV, like:

```
   - fn: vectordatasource.transform.csv_match_properties
    resources:
      matcher:
        type: file
        init_fn: vectordatasource.transform.CSVMatcher
        path: spreadsheets/sort_rank/landuse.csv
    params:
      source_layer: landuse
      target_value_type: int
```

it's also where we perform expensive calculations like the landuse_kind "intercuts" or overlays:

```
   - fn: vectordatasource.transform.overlap
    params:
      base_layer: buildings
      cutting_layer: landuse
      attribute: kind
      target_attribute: landuse_kind
      cutting_attrs: { sort_key: 'sort_rank', reverse: True }
```
