### ISSUE TITLE
Adjust min_zoom of OSM highways and major roads to better match Natural Earth

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1279]
@sensescape is adding optional level of detail filters to Refill and is making use of the `min_zoom` to do the filtering. But for the roads layer there's a discontinuity between the Natural Earth data at zooms 0-7 and the OSM data that starts at 8. Many roads that _already_ showed up in earlier zooms only have a `min_zoom` of 8 set, when they should have an earlier zoom.

- https://github.com/tilezen/vector-datasource/blob/master/yaml/roads.yaml#L185-L204

```
  #############################################################
  #
  # OSM highway
  #
  #############################################################
  - filter:
      highway: motorway
    # min_zoom 8 ≤ any mz_calculate_path_major_route(), so skip
    min_zoom: 8
    table: osm
    output:
      <<: *osm_highway_properties
      <<: *osm_network
      kind: highway
      kind_detail: motorway
  - filter:
      highway: [trunk, primary]
    # min_zoom 8 ≤ any mz_calculate_path_major_route(), so skip
    min_zoom: 8
    table: osm
    output:
      <<: *osm_highway_properties
      <<: *osm_network
      kind: major_road
      kind_detail: {col: highway}
```
