### ISSUE TITLE
Inconsistency between Natural Earth and OSM road classes

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1280]
I think the general `kind: highway` part of this was intentional, but possibly not the `type: Major Highway` > `kind: highway`. Generally speaking that should have gotten `kind: major_road, kind_detail: trunk`.

- https://github.com/tilezen/vector-datasource/blob/master/yaml/roads.yaml#L139-L148

```
  - filter:
      scalerank: true
      featurecla: Road
      type: [Major Highway, Beltway, Bypass]
    min_zoom: scalerank
    table: ne
    output:
      <<: *ne_properties
      kind: highway
      kind_detail: trunk
```

**Comment by zerebubuth** [comment]
Just to be sure I've understood this correctly: We want the input features with `type` `Major Highway` to result in output features with `kind: major_road`? This is kinda confusing, since "major highway" does suggest a highway.

Should we also remove the `kind_detail: trunk` from the `Beltway` and `Bypass` output (assuming they're keeping the `kind: highway`)?

**Comment by nvkelso** [comment]
The intent was to better match the motorway versus trunk "highway" transition between zoom 7 and 8 and OSM and Natural Earth (see images and link below). 

But you're right – we need to ALSO combine this with Natural Earth's `expressway` = 1 tag to get the desired effect. Good catch!

So something more like this (assuming we import the `expressway` boolean from NE)?

```
  - filter:
      scalerank: true
      featurecla: Road
      type: Major Highway
      expressway: 1
    min_zoom: scalerank
    table: ne
    output:
      <<: *ne_properties
      kind: highway
      kind_detail: motorway
  - filter:
      scalerank: true
      featurecla: Road
      type: [Beltway, Bypass]
      expressway: 1
    min_zoom: scalerank
    table: ne
    output:
      <<: *ne_properties
      kind: highway
      kind_detail: motorway
  - filter:
      scalerank: true
      featurecla: Road
      type: Major Highway
    min_zoom: scalerank
    table: ne
    output:
      <<: *ne_properties
      kind: major_road
      kind_detail: trunk
  - filter:
      scalerank: true
      featurecla: Road
      type: [Beltway, Bypass]
    min_zoom: scalerank
    table: ne
    output:
      <<: *ne_properties
      kind: major_road
      kind_detail: trunk
```

Here's a view of northern California:

http://tangrams.github.io/bubble-wrap/#8/39.637/-123.054

<img width="851" alt="Screen Shot 2019-04-16 at 00 48 51" src="https://user-images.githubusercontent.com/853051/56191806-f12c3f80-5fe1-11e9-8d2b-14abcd7a840e.png">
<img width="483" alt="Screen Shot 2019-04-16 at 00 51 55" src="https://user-images.githubusercontent.com/853051/56191804-f093a900-5fe1-11e9-83a5-5c7279074f38.png">
<img width="677" alt="Screen Shot 2019-04-16 at 00 48 43" src="https://user-images.githubusercontent.com/853051/56191807-f12c3f80-5fe1-11e9-8745-4b1993e5beb1.png">
