### ISSUE TITLE
Customized min_zoom for transit, bike

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1306]
Similar to https://github.com/tilezen/vector-datasource/issues/1248 which suggests custom sort_rank for the bike map mode, there are cases where the `min_zoom` should be different for default (driving) versus bike versus transit.

Primarily we're optimized for driving now, and we sometimes overstuff the tiles other content if it's deemed critical for a different map mode. For example: stations.

Right now we introduce most transit `station` features in the **pois** layer at zoom 10 for our transit overlay, but then in the stylesheet we filter out most of theme at lower zooms based on the `tile_kind_rank` values. So in this case the transit mode `min_zoom` should be 10, but the default `min_zoom` should align more closely with the default Mapzen basemap compilation reveal (a few at zoom 10, a few more at zoom 11, a few more at 12, more at 13, most at 14, all at 15).

This would require changing the `min_zoom` filters at the core of Tilezen to take the minimum across a set of "min_zoom" properties when testing if the feature should be exported for a tile.

```
        station-train-subway:
            filter: { kind: [station, train_station] }
            draw:
                colorized-icons:
                    visible: global.icon_visible_station
                    size: [[13, 12px], [14, 12px], [15, 16px], [17, 18px], [18, 20px]]
                    priority: 42
                    text:
                        visible: global.text_visible_station
            station-early:
                filter:
                    $zoom: { max: 11 }
                draw:
                    colorized-icons:
                        visible: false
            # for a transit style we'd want to see **all**, so don't move this above (it's special to this style)
            low-priority-early:
                filter: { kind_tile_rank: { min: 5 }, $zoom: { min: 0, max: 13 } }
                draw:
                    colorized-icons:
                        visible: false
            low-priority-early-z13:
                filter: { kind_tile_rank: { min: 5 }, $zoom: [13] }
                draw:
                    colorized-icons:
                        visible: false
            low-priority-early-z14:
                filter: { kind_tile_rank: { min: 7 }, $zoom: [14] }
                draw:
                    colorized-icons:
                        text: { visible: false }
```

/cc @sensescape who discovered the hard `min_zoom` of 10 for stations while working on Refill level of detail sprint.
