### ISSUE TITLE
provide segregated=true/false also on lower zoom levels

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1316]
* **What did you see?**
segregated=false/true is available only on z15+

* **What did you expect to see?**
I plan using this data on zoom levels lower than z15 (it would make sense even for z11 for cycling map to decide whatever path should be displayed, but at that zoom levels paths are anyway not displayed)

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

https://mapzen.com/tangram/play/?#15.0000/50.0820/19.8869

map style used for testing (yes, functions are necessary - filtering on `segregated: false` will merely check whatever property `segregated` is present):

```
# CC0 license

sources:
    mapzen:
        type: TopoJSON #GeoJSON, MVT, TopoJSON
        url:  https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson

camera:
    type: isometric

scene:
    background:
        color: white

layers:
    roads:
        data: { source: mapzen, layer: roads }
        highway:
            draw:
                lines:
                    order: 1300
                    color: white
                    cap: round
                    width: 8px
                    outline:
                        order: 1010
                        color: black
                        width: 1px
                        cap: butt
            green:
                filter: |
                    function () {
                        return (feature.segregated == true);
                    }
                draw:
                    lines:
                        color: green
            red:
                filter: |
                    function () {
                        return (feature.segregated == false);
                    }
                draw:
                    lines:
                        color: red
```

**Comment by nvkelso** [comment]
Seems like a reasonable match / consistent with: https://github.com/tilezen/vector-datasource/issues/1252.

**Comment by nvkelso** [comment]
BTW, you should be able to do something like:

```
            green:
                filter: { segregated: [true] }
                draw:
                    lines:
                        color: green
```
