### ISSUE TITLE
Consider dropping access=yes and related tags

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1331]
Picking up from https://github.com/tilezen/vector-datasource/pull/1328 it looks like we allow `access=*` and `motor_vehicle =*` at early zooms. We should either consider dropping `access=no` related features at low zooms, or at least drop `access=yes` properties from features at all (or just low) zooms to promote more feature merging to achieve smaller tile size and better label rendering. 

#### access=* related tags we use now:

- [ ] `access=*`
- [ ] `surface=*`
- [ ] `vehicle=*`
- [ ] `motor_vehicle=*`
- [ ] `bicycle=*`
- [ ] `foot:*`
- [ ] `horse=*`
- [ ] `ski=*`
- [ ] `snowmobile=*` (we [reference](https://github.com/tilezen/vector-datasource/blob/71e9e131aa7044b4cb1b31163a9931054e425809/yaml/roads.yaml#L366) snowmobile=designated but don't seem to actually export the `snowmobile` tag now, a bug?
- [ ] `snowshoe=*`

#### network related:

- [ ] cycleway network at low and mid zooms (should mostly just be the boolean `is_bicycle_related`)
- [ ] but networks (network, shields) at low and mid zooms (should just be `is_bus_route`)

**Comment by matkoniecz** [comment]
>  We should either consider dropping access=no related features at low zooms

Probably also access=private.

Note that access tag may be overridden - for example [highway=track + access=no + bicycle=designated] should not be displayed later than [highway = cycleway].

**Comment by matkoniecz** [comment]
motor_vehicle=yes in many cases is thoroughly useless and may be safely dropped ( https://josm.openstreetmap.de/browser/josm/trunk/data/validator/unnecessary.mapcss#L2 )

[motor_vehicle=yes][vehicle!=no][access!=no][bicycle_road!=yes][highway =~ /motorway|trunk|primary|secondary|tertiary|unclassified|residential|service|living_street/]

(used to appearing very often, still appears after years of JOSM validator rule - http://overpass-turbo.eu/s/qx5 , not sure about effects).

**Comment by nvkelso** [comment]
@matkoniecz Thanks for the tips and background :)

**Comment by nvkelso** [comment]
At 11/37.9675/-122.4409

![image](https://user-images.githubusercontent.com/853051/48571221-2dd0ff00-e8bb-11e8-87dd-d24e38e4ae98.png)

**Comment by nvkelso** [comment]
For bicycle, we can always keep the `is_bicycle_related` and strip off the network and shield text using following logic from Walkabout.

```
        #network_icn_ncn always visible, controlled by server
        network_rcn:
            filter: { bicycle_network: rcn, $zoom: { max: 12 } }
            draw:
                mapzen_icon_library:
                    visible: false
        tracks_network_rcn:
            filter: { $zoom: { max: 12 }, kind_detail: track }
            draw:
                mapzen_icon_library:
                    visible: false
        network_lcn:
            filter: { bicycle_network: lcn, $zoom: { max: 15 } }
            draw:
                mapzen_icon_library:
                    visible: false
```
