### ISSUE TITLE
Prefer forest labels over wilderness at zoom 7

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1608]
Wilderness and other "forest" features should probably only come in starting at zoom 7, and give deference to national_park features.

zoom 5

![image](https://user-images.githubusercontent.com/853051/45982244-d9bd4300-c00c-11e8-81d0-cf8f3d7c72cb.png)

zoom 7 @ 7/39.465/-477.706.

![image](https://user-images.githubusercontent.com/853051/45982204-b2ff0c80-c00c-11e8-8bc6-0e7f64069e92.png)

zoom 8

![image](https://user-images.githubusercontent.com/853051/45982294-0a04e180-c00d-11e8-8807-15c841e542bf.png)

**Comment by nvkelso** [comment]
Here's what the stylesheet is doing now, let's move this server side:

```
            landuse-labels-green-areas-not-national-park:
                filter:
                    kind: [park, conservation, protected_area, nature_reserve, forest, grass]
                    any:
                    # show labels for smaller landuse areas at higher zooms
                    - { $zoom: { max: 6 }, area: true }
                    - { $zoom: [6],    area: { max: 5000000000 } }
                    - { $zoom: [7],    area: { max: 5000000000 } }
                    - { $zoom: [8],    area: { max: 1000000000 } }
                    - { $zoom: [9],    area: { max: 100000000 } }
                    - { $zoom: [10],   area: { max: 50000000 } }
                    - { $zoom: [11],   area: { max: 25000000 } }
                    - { $zoom: [12],   area: { max: 5000000 } }
                    - { $zoom: [13],   area: { max: 200000 } }
                    - { $zoom: [14],   area: { max: 50000 } }
                    - { $zoom: [15],   area: { max: 10000 } }
                    - { $zoom: [16],   area: { max: 1000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
                wilderness-areas-early:
                    filter: function() { return $zoom < 9 && feature.name && (feature.name.indexOf("Wilderness") > -1 || feature.name.indexOf("BLM") > -1 || feature.protect_class == '1' || feature.protect_class == '1a' || feature.protect_class == '1b' ); }
                    draw:
                        mapzen_icon_library:
                            visible: false
                not-national-park:
                    filter: function() { return feature.name && !((feature.name.indexOf("National Park") > -1) || feature.name.indexOf("National Monument") > -1); }
                    early:
                        filter: { $zoom: { max: 8 } }
                        draw:
                            mapzen_icon_library:
                                visible: false
```
