### ISSUE TITLE
Many small parks and nature_reserves labeled as pois at zoom 10

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1609]
10/37.5331/-482.0698

![image](https://user-images.githubusercontent.com/853051/45982350-4c2e2300-c00d-11e8-85a0-12033fcfffd4.png)

Too small, icon covers it up completely, more appropriate for zoom 12:

- https://www.openstreetmap.org/way/43449405#map=12/37.4491/-121.8550

![image](https://user-images.githubusercontent.com/853051/45982395-7bdd2b00-c00d-11e8-89d4-1c9f7f6a8802.png)

Big enough for icon + polygon to show, but really show at 11:

- https://www.openstreetmap.org/way/39339860#map=11/37.3993/-121.8040

![image](https://user-images.githubusercontent.com/853051/45982423-91525500-c00d-11e8-8857-182de21735af.png)

**Comment by nvkelso** [comment]
Seems to be related to:

```
  - filter:
      any:
        leisure: park
        landuse: park
        boundary: national_park
    min_zoom: { min: [ { max: [ 9, { sum: [ { col: zoom }, 2 ] }, *tier2_min_zoom ] }, 14 ] }
    output:
      <<: *output_properties
      kind: park
      tier: 2
```

Which uses:

```
  - &tier2_min_zoom
    lookup:
      key: { col: way_area }
      op: '>='
      table:
        - [ 4, 1000000000 ]
        - [ 5, 1000000000 ]
        - [ 6,  150000000 ]
        - [ 7,  100,000,000 ]
        - [ 8,   10,000,000 ]   # 15,396,834 san bruno at zoom 10
        - [ 9,    5,000,000 ]   #4,451,500 alum rock park at zoom 11
        - [ 10,   1,000,000 ]    # 3,807,010 ed lavin park at zoom 12
                                           # same for John McClaren at 2,311,825 to zoom 12
        - [ 11,    500,000 ]     #    627,235 mount sutro at zoom 13
                                           # same for Glen Park Canyon at 415,605 to zoom 13
        - [ 12,    250,000 ]
        - [ 13,    100,000 ]
        - [ 14,     50000 ]
        - [ 15,      2000 ]
      default: 16
```

Maybe to:

```
  - &tier2_min_zoom_small_parks
    lookup:
      key: { col: way_area }
      op: '>='
      table:
        - [ 8,   160000000 ]
        - [ 9,    40000000 ]
        - [ 10,   10000000 ]
        - [ 11,    4000000 ]
        - [ 12,    2000000 ]
        - [ 13,    200000 ]
        - [ 14,     100000 ]
        - [ 15,      10000 ]
      default: 16
```

Which allows for smaller national parks to show up (good), but then smaller general parks should NOT show up, so split off a different tier breaks just for this filter? Starting at zoom 8 seems consistent with OSM.org styling, too.

- Adirondack Park, zoom 8, https://www.openstreetmap.org/relation/1695394#map=8/43.975/-74.325
- Humboldt Redwoods State zoom 9, https://www.openstreetmap.org/relation/181771#map=9/40.3319/-124.0109
- See zoom 10 example below for `nature_reserve`...
- San Bruno: https://www.openstreetmap.org/way/38414287#map=11/37.6860/-122.4347
- John McLaren Park, zoom 12: https://www.openstreetmap.org/way/28716696#map=12/37.71750/-122.41748
- Mount Sutro https://www.openstreetmap.org/relation/3307684#map=13/37.7593/-122.4560
- Glen Park canyon: https://www.openstreetmap.org/way/35800082#map=13/37.73963/-122.44108
- Bernal Heights Park, zoom 13, https://www.openstreetmap.org/way/16752188#map=13/37.7434/-122.4138
- Buena Vista Park, zoom 14: https://www.openstreetmap.org/way/7459901#map=14/37.76827/-122.44151
- Angelo Rossi Park, zoom 15: https://www.openstreetmap.org/way/69032470#map=15/37.77879/-122.45756
- Grattan Playground way too small, gets zoom 16 default: https://www.openstreetmap.org/way/27092661#map=16/37.76257/-122.45153
- Node default to zoom 16 for 29th & Diamond Open Space: https://www.openstreetmap.org/node/1004280495#map=16/37.7436/-122.4352

Also affecting **nature_reserve**:

- Ohlone Regional Wilderness: https://www.openstreetmap.org/way/43985377#map=10/37.5348/-121.7011
- Pescadero Marsh Natural Preserve: https://www.openstreetmap.org/way/39394133#map=12/37.2599/-122.4110
