### ISSUE TITLE
Cemetery too early

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1611]
Should match graveyard at zoom 13 min (from 12 now):

13/37.6768/-482.4012

![image](https://user-images.githubusercontent.com/853051/45982667-78966f00-c00e-11e8-9cd2-3b6e47b4732a.png)

**Comment by nvkelso** [comment]
```
            cemetery-early:
                filter:
                    kind: [cemetery]
                    # limit show smaller landuse areas to higher zooms
                    any:
                        - { $zoom: [12], area: { max: 3000000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
```
