### ISSUE TITLE
Remove kind_detail on populated places

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1613]
We can set a default population value on these, but we shouldn't also export the kind_detail.

eg:

```
  - filter: {name: true, place: isolated_dwelling}
    min_zoom: 13
    output:
      <<: *output_properties
      kind: locality
      kind_detail: isolated_dwelling
    table: osm
```
