### ISSUE TITLE
Don't include glacier POIs until zoom 14 when no area

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1617]
```
            glacier:
                filter: { $zoom: { max: 14 }, kind: glacier, area: false }
                draw:
                    mapzen_icon_library:
                        visible: false
```
