### ISSUE TITLE
Hide earlier offices

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1618]
```
            office-early:
                filter:
                    - { kind: [insurance, office, company], $zoom: [15], area: { max: 10000 } }
                    - { kind: [insurance, office, company], $zoom: [16], area: { max: 5000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
```
