### ISSUE TITLE
Hide some earlier golf courses

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1619]
```
            golf_course-early:
                filter:
                    kind: golf_course
                    any:
                        - { $zoom: [12], area: { max: 2500000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
```
