### ISSUE TITLE
Earlier gardens

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1620]
```
            garden-area-early:
                filter:
                    kind: [garden, allotments]
                    any:
                        # limit show smaller landuse areas to higher zooms
                        - { $zoom: [12], area: { max: 500000 } }
                        - { $zoom: [13], area: { max: 100000 } }
                        - { $zoom: [14], area: { max: 10000 } }
                        - { $zoom: [15], area: { max: 5000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
```

**Comment by nvkelso** [comment]
Related to garden change for no-area in https://github.com/tilezen/vector-datasource/issues/1636.

**Comment by nvkelso** [comment]
```
  - filter:
      leisure: garden
      not: { access: [ "private", "no" ] }
    min_zoom: { min: [ { max: [ 12, { col: zoom }, *tier6_min_zoom ] }, 16 ] }
    output:
      <<: *output_properties
      kind: garden
      tier: 6
```
