### ISSUE TITLE
Hide early university, college

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1622]
```
            university-early:
                filter:
                    kind: [university, college]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [11], area: { max: 2000000 } }
                        - { $zoom: [12], area: { max: 500000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
```
