### ISSUE TITLE
Hide early military

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1623]
```
            # hide based on kind and area filters
            military-early:
                filter:
                    kind: [military]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [8], area: { max: 50000000 } }
                draw:
                    mapzen_icon_library:
                        visible: false
```
