### ISSUE TITLE
Hide early bike parking, car sharing

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1624]
```
            hide-until-z19-any:
                filter:
                    $zoom: { max: 19 }
                    kind: [bicycle_parking, burial_vault, car_sharing]
                draw:
                    mapzen_icon_library:
                        visible: false
```
