### ISSUE TITLE
Hide early parking when no area, show parking areas earlier

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1625]
```
            hide-until-z18-no-area:
                filter:
                    $zoom: { max: 18 }
                    area: false
                    kind: [bench, parking, waste_basket]
                draw:
                    mapzen_icon_library:
                        visible: false
```
