### ISSUE TITLE
Hide early atm, bus_stop, drinking_water, post_box, telephone

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1626]
tl;dr 

It's a little more widespread then this, see next comment.

```
            hide-until-z18-any:
                filter:
                    kind: [atm, bus_stop, drinking_water]
                    $zoom: { max: 18 }
                draw:
                    mapzen_icon_library:
                        visible: false
```
