### ISSUE TITLE
Modify zoom of bicycle, theatre, water_tower

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1627]
tl;dr

Only bicycle, theatre, and water_tower are relevant here. See comment below.

```
            hide-until-z17-no-area:
                filter:
                    area: false
                    $zoom: { max: 17 }
                    # note: atm and drinking_water appear hear and in area versions
                    kind: [accountant, administrative, advertising_agency, animal, architect, association, atm, bakery, bed_and_breakfast, bicycle, bicycle_parking, bicycle_rental_station, books, butcher, car, car_repair, chalet, clothes, company, computer, consulting, convenience, doityourself, drinking_water, dry_cleaning, educational_institution, emergency_phone, employment_agency, estate_agent, fashion, financial, florist, foundation, gift, government, greengrocer, guest_house, hairdresser, hostel, hotel, insurance, it, jewelry, lawyer, mast, memorial, mobile_phone, motel, newspaper, ngo, notary, optician, parking, pet, physician, playground, political_party, post_box, religion, research, subway_entrance, tax_advisor, telecommunication, telephone, theatre, therapist, toilets, traffic_signals, travel_agent, water_tower]
                draw:
                    mapzen_icon_library:
                        visible: false

```

**Comment by nvkelso** [comment]
Change these, for no-area (node) case:

- **bicycle** shop (zoom 15 now, might interfere with Walkabout bike overlay, consider 16 instead?), really this should be an area throttle, similar to cafe?
    - bike node, to zoom 17: https://www.openstreetmap.org/node/2484293076#map=19/37.77108/-122.43223
    - bike way, to zoom 16?: https://www.openstreetmap.org/way/260354461#map=16/37.7771/-122.4077
    - bike way, to zoom 15? https://www.openstreetmap.org/way/264534357#map=15/37.7665/-122.4527

Maybe:

```
  - filter: {shop: bicycle}
    min_zoom: { clamp: { min: 15, max: 17, value: { sum: [ { col: zoom }, 2.5 ] } } }
    output:
      <<: *output_properties
      kind: bicycle
```

- **theatre** from zoom 16 now, but it already has an area throttle, so peal off to it's own? 
    - node, zoom 17?: https://www.openstreetmap.org/node/358805392#map=17/37.78302/-122.41223
    - medium way, zoom 16?: https://www.openstreetmap.org/way/35115840#map=16/37.7793/-122.4146
    - large way, zoom 15? https://www.openstreetmap.org/way/266170808#map=15/40.7598/-73.9793
    - This area of NYC has tons of theatres: https://www.openstreetmap.org/#map=16/40.7604/-73.9860

Maybe:

```
  - filter:
      amenity: theatre
    min_zoom: { clamp: { min: 15, max: 17, value: { sum: [ { col: zoom }, 2.7 ] } } }
    output:
      <<: *output_properties
      kind: theatre
```

- **water_tower** (from zoom 15 always, should have a height throttle?
    - node: https://www.openstreetmap.org/way/247759532#map=19/37.76116/-122.44618
    - way with 9 meter height: https://www.openstreetmap.org/way/269308993#map=19/37.74832/-122.46736
    - way with 20+ meter height: https://www.openstreetmap.org/way/424957085#map=19/37.72314/-122.42432

Suggest riffing on what we do for `obelisk` for `water_tower`, maybe:

```
  - filter: {man_made: water_tower}
    min_zoom:
      lookup:
        key: { call: { func: mz_to_float_meters, args: [ { col: height } ] } }
        op: '>='
        table:
          - [ 15, 20 ]  # z15 if height >= 20m
          - [ 16, 10 ]  # z15 if height >= 10m
        default: 17
```


**These are already zoom 17, no change needed:**

accountant
administrative
advertising_agency
animal
architect
association
atm
bakery
bed_and_breakfast
bicycle_parking
bicycle_rental_station
books
butcher
car
car_repair
chalet
clothes
company
computer
consulting
convenience
drinking_water
dry_cleaning
educational_institution
emergency_phone
employment_agency
estate_agent
fashion
financial
florist
foundation
gift
government
greengrocer
guest_house
hairdresser
hostel
hotel
insurance
it
jewelry
lawyer
mast
memorial (already lots of complicated logic added for this one)
mobile_phone
motel
newspaper
ngo
notary
optician
parking
pet
physician
playground
political_party
post_box
religion
research
subway_entrance
tax_advisor
telecommunication
telephone
therapist
toilets (already 18)
traffic_signals
travel_agent
doityourself
