### ISSUE TITLE
Hide pitch until zoom 17

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1628]
tl;dr

Only `pitch` is actionable in the list below. Right now it defaults to zoom 16, it should be zoom 17 default instead.

```
            hide-until-z17-with-area:
                filter:
                    area: true
                    $zoom: { max: 17 }
                    kind: [common, grass, houseboat, pedestrian, pitch, railway, ship, wetland]
                draw:
                    mapzen_icon_library:
                        visible: false
```
