### ISSUE TITLE
Move POI label to landuse labels

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1629]
```
        suppress-icon-z17:
            filter:
                $zoom: { min: 17 }
                kind: [common, grass, houseboat, pedestrian, railway, ship, wetland]
            draw:
                mapzen_icon_library:
                    visible: false
                    text: { font: { style: italic } }
```
