### ISSUE TITLE
Hide early landmark, museum, prison

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1630]
```
            hide-until-z12-any:
                filter:
                    kind: [landmark, museum, prison]
                    $zoom: { max: 12 }
                draw:
                    mapzen_icon_library:
                        visible: false
```

**Comment by nvkelso** [comment]
Looks like we mod the min to be 12 instead of 0 here?

```
  - filter: {amenity: prison}
    min_zoom: { clamp: { min: 0, max: 15, value: { sum: [ { col: zoom }, 2.55 ] } } }
    output:
      <<: *output_properties
      kind: prison
  - filter: {tourism: museum}
    min_zoom: { clamp: { min: 0, max: 16, value: { sum: [ { col: zoom }, 1.43 ] } } }
    output:
      <<: *output_properties
      kind: museum
  - filter: {historic: landmark}
    min_zoom: { clamp: { min: 0, max: 15, value: { sum: [ { col: zoom }, 1.76 ] } } }
    output:
      <<: *output_properties
      kind: landmark
```
