### ISSUE TITLE
Hide early post_office

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1631]
```
            hide-until-z14-any:
                filter:
                    kind: [natural_forest, natural_park, natural_wood, post_office]
                    $zoom: { max: 14 }
                draw:
                    mapzen_icon_library:
                        visible: false
```
