### ISSUE TITLE
Hide early cafe, restaurant to zoom 15

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1632]
```
            hide-until-z15-any:
                filter:
                    $zoom: { max: 15 }
                    kind: [cafe, restaurant]
                draw:
                    mapzen_icon_library:
                        visible: false
```
