### ISSUE TITLE
Hide early parks that don't have area to zoom 15

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1633]
```
            hide-until-z15-no-area:
                filter:
                    area: false
                    $zoom: { max: 15 }
                    kind: [park]
                draw:
                    mapzen_icon_library:
                        visible: false
```
