### ISSUE TITLE
Hide early nursing_home to zoom 15

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1634]
```
            hide-until-z15-with-area:
                filter:
                    area: true
                    $zoom: { max: 15 }
                    kind: [nursing_home]
                draw:
                    mapzen_icon_library:
                        visible: false
```
