### ISSUE TITLE
Hide early tram_stop, halt, stop to zoom 16

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1635]
```
            hide-until-z16-any:
                filter:
                    kind: [fire_station, grass, peak, police, tram_stop]
                    $zoom: { max: 16 }
                draw:
                    mapzen_icon_library:
                        visible: false
```
