### ISSUE TITLE
Hide early no-area garden, university, and add allotments

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1636]
```
            hide-until-z16-no-area:
                filter:
                    area: false
                    kind: [allotments, college, garden, university]
                    $zoom: { max: 16 }
                draw:
                    mapzen_icon_library:
                        visible: false
```
