### ISSUE TITLE
Hide early wood, platform to zoom 17

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1637]
```
            hide-until-z17-any:
                filter:
                    $zoom: { max: 17 }
                    kind: [bank, bus_stop, car_sharing, wood, platform]
                draw:
                    mapzen_icon_library:
                        visible: false
```
