### ISSUE TITLE
Further water layer name dropping at low zooms

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1730]
Following up from https://github.com/tilezen/vector-datasource/issues/1477 and https://github.com/tilezen/vector-datasource/pull/1714/files, and based on original zoom & area table in https://github.com/tilezen/vector-datasource/issues/1477#issuecomment-442269890.

We can drop even more water layer labels derived from polygons at zooms 0-5.

Zooms 6+ seems mostly okay. But I don't understand how that works... seems like we drop water labels based on a width / area treshhold – where does that happen?

But there's also funk with how the Natural Earth names are brought in at low zooms which make it look better than it should? Example at bottom.

**Need to change so:** 

- [ ] No lake labels at zoom 0-3
- [ ] Then zoom 4 and 5 have different threshold:
- [x] Then zoom 6+ no change? Might need zoom 6,7 for Natural Earth of the area threshold is OSM only?

```
                        - { $zoom: { min: 4 },  area: { min: 40000000000 } }
                        - { $zoom: { min: 5 },  area: { min: 10000000000 } }
```

The original in https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L1258-L1279

```
        water-area-labels:
            visible: global.text_visible_water_labels
            filter:
                all:
                    - name: true
                    - $geometry: point
                    - not: { kind: [riverbank, dock, playa] }
                    - area: true
                any:
                    # show labels for smaller landuse areas at higher zooms
                    - { $zoom: { min: 5 },  area: { min: 10000000000 } }
                    - { $zoom: { min: 6 },  area: { min: 5000000000 } }
                    - { $zoom: { min: 7 },  area: { min: 400000000 } }
                    - { $zoom: { min: 8 },  area: { min: 200000000 } }
                    - { $zoom: { min: 9 },  area: { min: 100000000 } }
                    - { $zoom: { min: 10 }, area: { min: 10000000 } }
                    - { $zoom: { min: 11 }, area: { min: 4000000 } }
                    - { $zoom: { min: 12 }, area: { min: 750000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 10000 } }
                    - { $zoom: { min: 16 } }
```

Desired at zoom 4:

![image](https://user-images.githubusercontent.com/853051/49975134-692e1000-fef1-11e8-8caa-76b46d88acbc.png)

Present in v1.6c:

![image](https://user-images.githubusercontent.com/853051/49975190-a5617080-fef1-11e8-98d0-1cf44185d993.png)

Desired at zoom 5:

![image](https://user-images.githubusercontent.com/853051/49975148-7e0aa380-fef1-11e8-958e-dace12d37380.png)

Present in v1.6c:

![image](https://user-images.githubusercontent.com/853051/49975169-97135480-fef1-11e8-9bfd-2e16a3243118.png)

Notice how there's no default name here, but there is `name:en`:

6/40.772/-116.609

![image](https://user-images.githubusercontent.com/853051/49975357-78fa2400-fef2-11e8-9602-89792ac858a5.png)

**Comment by nvkelso** [comment]
Doesn't look like this is on dev yet.

**Comment by zerebubuth** [comment]
That's weird. I was pretty sure we made the cut-off for this one, and I'm seeing the sort of things I'd expect on dev. For example, I just checked:

1. The lakes are not named at zoom 3.
2. Only the largest at zoom 4. For example; Lake Winnipeg is named, Reindeer Lake is not.
3. Smaller lakes at zoom 5 not named. For example; Reindeer Lake is now named, Wollaston Lake is not.
4. All names dropped from Pyramid Lake at zoom 6, all names present at zoom 7.

It's possible that there's some other example that I've missed, or a bug which is making it look like it's not on dev properly. If so, please share an example and I'll check it out.

**Comment by nvkelso** [comment]
Here's what I see, using Bubble Wrap and the following local config (removes the any clause, too), using the dev server:

```
        water-labels:
            filter:
                all:
                    - name: true
                    - function() { return global.text_visible_water_labels; }
                    - $zoom: { min: 1 }
            water-area-labels:
                filter:
                    all:
                        - $geometry: point
                        - not: { kind: [riverbank, dock, playa] }
                        - area: true
                default-label-text:
                    draw:
                        text-blend-order:
                            text_source: global.ux_language_text_source
                            text_wrap: 10
                            font:
                                fill: [0.314,0.591,0.640] #global.text_fill_water
                                family: global.text_font_family
                                style: italic
                                weight: normal
                                size: [[6,10px],[6,12px]]
```

> 1. The lakes are not named at zoom 3.

![image](https://user-images.githubusercontent.com/853051/51640069-69b9bd80-1f17-11e9-93f5-318f4244fa5a.png)

![image](https://user-images.githubusercontent.com/853051/51640099-763e1600-1f17-11e9-8826-1b581324b9c0.png)

![image](https://user-images.githubusercontent.com/853051/51640115-80601480-1f17-11e9-98bd-780e6a99e4d6.png)

> 2. Only the largest at zoom 4. For example; Lake Winnipeg is named, Reindeer Lake is not.

![image](https://user-images.githubusercontent.com/853051/51640152-940b7b00-1f17-11e9-9412-7986b38c7d28.png)

> 3. Smaller lakes at zoom 5 not named. For example; Reindeer Lake is now named, Wollaston Lake is not.

![image](https://user-images.githubusercontent.com/853051/51640171-a4235a80-1f17-11e9-8934-c21f72d8643c.png)

> 4. All names dropped from Pyramid Lake at zoom 6, all names present at zoom 7.

![image](https://user-images.githubusercontent.com/853051/51640199-b30a0d00-1f17-11e9-8886-0572cacdb8d6.png)

![image](https://user-images.githubusercontent.com/853051/51640214-be5d3880-1f17-11e9-9a55-64384f23fd11.png)

![image](https://user-images.githubusercontent.com/853051/51640225-c9b06400-1f17-11e9-9e27-6cbe6f1a5354.png)
