### ISSUE TITLE
Address points have surplus properties

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#2024]
The only thing we really need for display is the address number, all the other properties just add fake database bulk to the payload.

- https://github.com/tilezen/vector-datasource/blob/master/yaml/buildings.yaml#L129-L139

```
  # address points
  - filter:
      "addr:housenumber": true
      geom_type: point
    extra_columns: [way]
    min_zoom: 17
    output:
      <<: *output_properties
      kind: address
      addr_housenumber: {col: 'addr:housenumber'}
      addr_street: {col: 'addr:street'}
```

With [*output_properties](https://github.com/tilezen/vector-datasource/blob/master/yaml/buildings.yaml#L6-L15) being:

```
  - &output_properties
    area:
      call:
        func: util.safe_int
        args: [ { col: area } ]
    label_placement: {col: label_placement}
    min_zoom: {col: min_zoom}
    mz_label_placement: {col: mz_label_placement}
    name: {col: name}
    source: {col: source}
```

The property that cause the most bulk are:

- addr_street

These other properties are sometimes populated but aren't useful:

- name
- label_placement
- kind_detail
- landuse_kind
- osm_relation

If the property appears in the buildings.yaml then it should be removed.

To make 2x sure it's no longer there we can strip propes in the queries.yaml, right after the way-based address points are generated:

- https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L937-L940

WARNING: removing properties invokes https://github.com/tilezen/vector-datasource/blob/master/docs/SEMANTIC-VERSIONING.md so this is 2.0 territory.

Related: https://github.com/tilezen/vector-datasource/issues/2023.
