### ISSUE TITLE
Improve logic & perf of landuse drawing (server-client)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#473]
There are ~5 tiers of landuse types with different area thresholds per zoom. These nested filters cause performance issues in Tangram (and other client side mapping libraries). Historically we've included any landuse (and water) that is above a pixel threshold. We should still do that, but also decorate them with a new "more-or-less" style attribute that is set based on the features effective `min_zoom` (calculated from the area filters). Want all the parks? Only want the biggest? Want something in between? This could allow a simple boolean evaluation client side instead of the per zoom filters, improving perf.

**WARNING!** Different settings for polygons versus their labels...

**Comment by nvkelso** [comment]
For example:

```
    landuse:
        data: { source: osm }
        tier1:
            filter: 
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 3 },  area: { min: 300000000 } }
                    - { $zoom: { min: 4 },  area: { min: 300000000 } }
                    - { $zoom: { min: 5 },  area: { min: 150000000 } }
                    - { $zoom: { min: 6 },  area: { min: 150000000 } }
                    - { $zoom: { min: 7 },  area: { min: 100000000 } }
                    - { $zoom: { min: 8 },  area: { min: 10000000 } }
                    - { $zoom: { min: 9 },  area: { min: 5000000 } }
                    - { $zoom: { min: 10 }, area: { min: 1000000 } }
                    - { $zoom: { min: 11 }, area: { min: 500000 } }
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 } }
            national_park:
                filter: { kind: [national_park, "park or protected land"], not: { operator: [ "United States Forest Service", "US Forest Service", "U.S. Forest Service", "USDA Forest Service" ] } }
                draw:
                    polygons:
                      color: *green7
                us_national_park:
                    # yosemite national park, death valley national park, grand canyon national park
                    filter: { operator: [ "United States National Park Service", "US National Park Service" ] }
                    draw:
                        polygons:
                            color: *green1
        tier2:
            filter: 
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 4 },  area: { min: 1000000000 } }
                    - { $zoom: { min: 5 },  area: { min: 1000000000 } }
                    - { $zoom: { min: 6 },  area: { min: 150000000 } }
                    - { $zoom: { min: 7 },  area: { min: 100000000 } }
                    - { $zoom: { min: 8 },  area: { min: 10000000 } }
                    - { $zoom: { min: 9 },  area: { min: 5000000 } }
                    - { $zoom: { min: 10 }, area: { min: 1000000 } }
                    - { $zoom: { min: 11 }, area: { min: 500000 } }
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 } }
            conservation:
                filter:
                    kind: [conservation, protected_area, nature_reserve]
                    $zoom: { min: 6 }
                draw:
                    polygons:
                        color: *green8
                wilderness-areas:
                    filter: function() { return feature.name && feature.name.indexOf("Wilderness") > -1 }
                    draw:
                        polygons:
                            color: [[5,*green7],[8,*green1_w]]
                        outline:
                            style: lines
                            order: 3
                            color: *green1_ws
                            width: [[9,0px],[10,1px],[11,2px],[12,4px]]
                national_forest_level_6:
                    filter: { protect_class: ["6",6] }
                    draw:
                        polygons:
                            color: *green7
                        lines:
                            order: 10
                            color: *earth1
                            width: 2px
            # gotta be a protected area to draw green, not just a landcover type
            farm:
                filter:
                    kind: [farm, farmland]
                    $zoom: { min: 10}
                draw:
                    polygons:
                        color: [ [10,*green4], [12,*green5] ]
                        visible: *green4_v
            forest:
                filter: { kind: [forest,wood], $zoom: { min: 6 } }
                national-forest:
                    filter:
                        operator: [ "United States Forest Service", "US Forest Service", "U.S. Forest Service", "USDA Forest Service" ]
                    draw:
                        polygons:
                            color: *green7
                        lines:
                            order: 10
                            color: *earth1
                            width: 2px
                landuse-forest:
                    filter:
                        not: { operator: [ "United States Forest Service", "US Forest Service", "U.S. Forest Service", "USDA Forest Service" ] }
                        $zoom: { min: 10 }
                    draw:
                        polygons:
                            color: *green9

            nature_reserve:
                filter: { kind: nature_reserve, $zoom: { min: 7 } }
                draw:
                    polygons:
                        color: *green6
                wilderness-areas:
                    filter: function() { return feature.name && feature.name.indexOf("Wilderness") > -1 }
                    draw:
                        polygons:
                            color: *green7
                        outline:
                            style: lines
                            color: *green6
                            width: [[9,0px],[10,2px],[12,4px]]
            parks-and-national-forests-not-national-park:
                filter: { $zoom: { min: 4 }, kind: [park, national_park, "park or protected land"], not: { operator: [ "United States National Park Service", "US National Park Service" ] } }
                # default for national forests and more?
                draw:
                    polygons:
                        color: *green7
                        order: function() { return feature.sort_key + 1 || 1; }
                    lines:
                        order: 3
                        color: *earth1
                        width: [[7,0px],[8,1px],[10,2px]]
            urban:
                filter: { kind: [urban, rural, residential] }
                visible: *earth2_v
                draw:
                    polygons:
                        color: [[0,*earth2],[9,*earth2]]
                        visible: *earth2_v
        tier3:
            filter: 
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 8 },  area: { min: 10000000 } }
                    - { $zoom: { min: 9 },  area: { min: 5000000 } }
                    - { $zoom: { min: 10 }, area: { min: 1000000 } }
                    - { $zoom: { min: 11 }, area: { min: 500000 } }
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 } }
            airport:
                filter:
                    kind: aerodrome
                draw:
                    polygons:
                        color: *purple
                        visible: *purple_v
            military:
                filter:
                    kind: military
                draw:
                    polygons:
                        color: *purple
            university:
                filter:
                    kind: university
                draw:
                    polygons:
                        color: *brown1
                        order: function() { return feature.sort_key - 2 || 1; }
        tier4:
            filter: 
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 10 }, area: { min: 1000000 } }
                    - { $zoom: { min: 11 }, area: { min: 500000 } }
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 } }
            cemetery:
                filter:
                    kind: cemetery
                draw:
                    polygons:
                        color: *green2
            commercial:
                filter:
                    kind: commercial
                draw:
                    polygons:
                        color: *grey1
                        visible: *grey1_v
            golf_course:
                filter:
                    kind: golf_course
                draw:
                    polygons:
                        color: *green3
            hospital:
                filter:
                    kind: hospital
                draw:
                    polygons:
                        color: *red1
            industrial:
                filter:
                    kind: industrial
                draw:
                    polygons:
                        color: *grey6
            power:
                filter: { kind: [plant, generator, substation] }
                draw:
                    polygons:
                        color: *grey3
            railway:
                filter:
                    kind: railway
                draw:
                    polygons:
                        color: *grey3
            sports_centre:
                filter:
                    kind: sports_centre
                draw:
                    polygons:
                        color: *green10
                        order: function() { return feature.sort_key + 1 || 1; }
            recreation_ground:
                filter:
                    kind: recreation_ground
                draw:
                    polygons:
                        color: *mystry1
            retail:
                filter:
                    kind: retail
                draw:
                    polygons:
                        color: *grey1
                        visible: *grey1_v
            stadium:
                filter:
                    kind: stadium
                draw:
                    polygons:
                        color: *orange1
            zoo:
                filter:
                    kind: zoo
                draw:
                    polygons:
                        color: *green2
            winter_sports:
                filter:
                    kind: winter_sports
                draw:
                    polygons:
                        color: *grey8
                        visible: *grey8_v
            man-made:
                filter: { kind: [pier,wastewater_plant,works,bridge,tower,breakwater,water_works,groyne,dike,cutline] }
                draw: { polygons: { order: 2, color: *grey3 } }
                pier:
                    filter: { kind: [pier,bridge,breakwater,groyne,dike,cutline] }
                    draw: { polygons: { order: 5, color: *earth1 } }
        tier5:
            filter: 
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 } }
            garden:
                filter:
                    kind: garden
                draw:
                    polygons:
                        color: *green2
                        order: 4
            parking:
                filter:
                    all:
                        - kind: parking
                        - $zoom: { min: 14 }
                    any:
                        - { $zoom: { min: 14 }, area: { min: 10000 } }
                        - { $zoom: { min: 15 }, area: { min: 5000 } }
                draw:
                    polygons:
                        color: *grey1
                        visible: *grey1_v
                early:
                    filter: { $zoom: { max: 15 } }
                    draw:
                        polygons:
                            color: *grey1_e
            pedestrian:
                filter:
                    kind: [pedestrian,common]
                draw:
                    polygons:
                        color: *grey7
                        visible: *grey7_v
            pitch:
                filter: { kind: pitch }
                draw:
                    polygons:
                        order: 7
                        color: *orange2
                    outline:
                        style: lines
                        color: *green6
                        width: [[14,0px],[15,1px],[16,1m]]
            place_of_worship:
                filter:
                    kind: place_of_worship
                draw:
                    polygons:
                        color: *grey1
                        visible: *grey1_v
            playground:
                filter:
                    kind: playground
                draw:
                    polygons:
                        color: *brown3
            school:
                filter:
                    kind: school
                draw:
                    polygons:
                        color: *brown2
        z-order:
            draw: 
                polygons: 
                    order: function() { return feature.sort_key || 1; }
```

**Comment by zerebubuth** [comment]
I'm not sure I understand the benefit of having different properties based on size. Would you be looking for a `size: (large|medium|small)` property, and instead of writing something like:

```yaml
        something:
            filter:
                all:
                    - kind: [kind1, kind2, kind3]
                any:
                    - { $zoom: { min: 1 },  area: { min: 40000000000 } }
                    - { $zoom: { min: 2 },  area: { min: 20000000000 } }
                    - { $zoom: { min: 3 },  area: { min: 80000000000 } }
                    - { $zoom: { min: 4 },  area: { min: 5000000000 } }
                    - { $zoom: { min: 5 },  area: { min: 700000000 } }
                    - { $zoom: { min: 6 },  area: { min: 500000000 } }
                    - { $zoom: { min: 7 },  area: { min: 160000000 } }
                    - { $zoom: { min: 8 },  area: { min: 40000000 } }
                    - { $zoom: { min: 9 },  area: { min: 10000000 } }
                    - { $zoom: { min: 10 }, area: { min: 8000000 } }
                    - { $zoom: { min: 11 }, area: { min: 2000000 } }
                    - { $zoom: { min: 12 }, area: { min: 500000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 2000 } }
                    - { $zoom: { min: 15 } }
```

Write something like this:

```yaml
        something:
            filter:
                  - kind: [kind1, kind2, kind3]
                  - $zoom: { min: min_zoom }
                  - size: [large, medium]
```

Would we get similar performance improvements by implementing a `min-per-zoom` function, for example something like:

```yaml
        something:
            filter:
                all:
                    - kind: [kind1, kind2, kind3]
                area: { min-per-zoom[
                  40000000000,
                  20000000000,
                  80000000000,
                  5000000000,
                  700000000,
                  500000000,
                  160000000,
                  40000000,
                  10000000,
                  8000000,
                  2000000,
                  500000,
                  100000,
                  2000 ] }
```

I know, the syntax for that is horrible, but it's a common pattern and it the name of the game is reducing the number of AST nodes in the filter that have to be evaluated, then this might work. @bcamper: am I understanding this right?

**Comment by bcamper** [comment]
@nvkelso can speak to the design needs, but currently a feature may be a "tier3", but is being subjected to a ton of unnecessary area/zoom filter checks for tiers 1, 2, 4, 5, etc. At least that's my understanding. Min-zoom-related logic is also relevant, but if we can both provide a significantly simplified stylesheet (for our own designs and others) and avoid client-side calculations by providing a hint as to the feature's importance (e.g. baking the tier1/2/3/4/5 calc into the tile), that seems worthwhile to me. (In this particular case, I'm assuming there aren't enough landuse polys at any time that the filters are a big performance -- I need to benchmark -- but the stylesheet complexity is high.)

**Comment by nvkelso** [comment]
There are two considerations: **logically** the cartographer should deal in "rule of 3" buckets and we should improve perf.

**Comment by nvkelso** [comment]
@bcamper reminds me that a lot of landuse labels are showing up far too early as data, and scene file filters them out. So just like the comment in the `water` issue, there should be different importance based on different area ranges for the labels (versus the features):

```
            landuse-labels-green-areas-national-park:
                filter:
                    all:
                        - area: true
                        - $geometry: point
                        - kind: [national_park, "park or protected land"]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [4],  area: { min: 3000000000 } }
                        - { $zoom: [5],  area: { min: 3000000000 } }
                        - { $zoom: [6],  area: { min: 500000000 } }
                        - { $zoom: [7,8,9],  area: { min: 100000000 } }
                        - { $zoom: [10], area: { min: 50000000 } }
                        - { $zoom: [11], area: { min: 25000000 } }
                        - { $zoom: [12], area: { min: 5000000 } }
                        - { $zoom: [13], area: { min: 200000 } }
                        - { $zoom: [14], area: { min: 50000 } }
                        - { $zoom: { min: 15 } }
                national-park:
                    filter: function() { return feature.name && feature.name.indexOf("National Park") > -1; }
                    visible: *label_visible_landuse_green
                    draw:
                        icons:
                            visible: *icon_visible_landuse_green
                            sprite: park
                            interactive: true
                        text:
                            visible: *text_visible_landuse_green
                            interactive: true
                            offset: [0, 14px]
                            font:
                                fill: *text_fill_park
                                size: 12px
                                style: italic
                                stroke: { color: *text_stroke_park, width: 4 }
            landuse-labels-green-areas-not-national-park:
                filter:
                    all:
                        - area: true
                        - $geometry: point
                        - kind: [park, national_park, "park or protected land",conservation, protected_area, nature_reserve, forest, grass]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [5],    area: { min: 10000000000 } }
                        - { $zoom: [6,7],  area: { min: 5000000000 } }
                        - { $zoom: [8],    area: { min: 1000000000 } }
                        - { $zoom: [9],    area: { min: 100000000 } }
                        - { $zoom: [10],   area: { min: 50000000 } }
                        - { $zoom: [11],   area: { min: 25000000 } }
                        - { $zoom: [12],   area: { min: 5000000 } }
                        - { $zoom: [13],   area: { min: 200000 } }
                        - { $zoom: [14],   area: { min: 50000 } }
                        - { $zoom: [15],   area: { min: 10000 } }
                        - { $zoom: [16],   area: { min: 1000 } }
                        - { $zoom: { min: 17 } }
                visible: *label_visible_landuse_green
                draw:
                    icons:
                        visible: *icon_visible_landuse_green
                        sprite: forest
                        interactive: true
                    text:
                        visible: *text_visible_landuse_green
                        interactive: true
                        offset: [0, 14px]
                        font:
                            fill: *text_fill_park
                            size: 12px
                            style: italic
                            stroke: { color: *text_stroke_park, width: 4 }
                wilderness-areas-early:
                   filter: function() { return $zoom < 10 && feature.name && (feature.name.indexOf("Wilderness") > -1 || feature.name.indexOf("BLM") > -1) }
                   draw:
                       text: { visible: false }
                       icons: { visible: false }
                early-not-national-park:
                    filter: { not: { kind: national_park }, $zoom: { max: 6 } }
                    draw:
                        text: { visible: false }
                        icons: { visible: false }
                not-national-park:
                    filter: function() { return feature.name && feature.name.indexOf("Park") > -1 && !feature.name.indexOf("National Park") > -1}
                    draw:
                        icons:
                            sprite: park
                    early:
                        filter: { $zoom: { max: 8 } }
                        draw:
                            text: { visible: false }
                            icons: { visible: false }
                forest:
                    filter: function() { return $zoom < 8 && ((feature.name && feature.name.indexOf("Forest") > -1) || feature.protect_class >=6) }
                    draw:
                        text: { visible: false }
                        icons: { visible: false }
                hide-till-later:
                    filter: { kind: [grass], $zoom: { max: 16 } }
                    draw:
                        text: { visible: false }
                        icons: { visible: false }
                only-text-later:
                    filter: { kind: [grass], $zoom: { min: 16 } }
                    draw:
                        text: { font: { style: italic } }
                        icons: { visible: false }
            airport:
                filter:
                    all:
                        - kind: [airport, aerodrome]
                        - area: true
                        - $geometry: point
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [9],  area: { min: 10000000 } }
                        - { $zoom: [10], area: { min: 10000000 } }
                        - { $zoom: [11], area: { min: 5000000 } }
                        - { $zoom: [12], area: { min: 5000000 } }
                        - { $zoom: [13], area: { min: 500000 } }
                        - { $zoom: [14], area: { min: 20000 } }                    
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [15], area: { min: 10000 } }
                        - { $zoom: [16], area: { min: 5000 } }
                        - { $zoom: [17], area: { min: 2000 } }
                        - { $zoom: { min: 18 } }
                draw:
                    text:
                        visible: *text_visible_landuse_green
                        interactive: true
                        font:
                            fill: *text_fill
                            size: 12px
                            stroke: { color: *text_stroke, width: 4 }
                    icons:
                        sprite: airport
                        visible: *icon_visible_landuse_green
                        interactive: true
                early:
                    filter: { $zoom: { max: 12 } }
                    # todo: huh?
                    draw: { text: { text_source: ref } }
            university:
                filter:
                    all:
                        - kind: [university,college]
                        - area: true
                        - $geometry: point
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [9],   area: { min: 10000000 } }
                        - { $zoom: [10], area: { min: 5000000 } }
                        - { $zoom: [11], area: { min: 2000000 } }
                        - { $zoom: [12], area: { min: 500000 } }
                        - { $zoom: [13], area: { min: 100000 } }
                        - { $zoom: [14], area: { min: 100000 } }
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [15], area: { min: 40000 } }
                        - { $zoom: [16], area: { min: 5000 } }
                        - { $zoom: [17], area: { min: 2000 } }
                        - { $zoom: { min: 18 } }
                visible: *label_visible_landuse_green
                draw:
                    text:
                        visible: *text_visible_landuse_green
                        interactive: true
                        font:
                            fill: *text_fill
                            size: 12px
                            stroke: { color: *text_stroke, width: 4 }
                    icons:
                        sprite: college-university
                        visible: *icon_visible_landuse_green
                        interactive: true
                early:
                    filter: { $zoom: { max: 14 } }
                    draw: { text: { font: { size: 11px } } }
            landuse-labels-not-green-areas:
                filter:
                    all:
                        - $zoom: { min: 6 }
                        - area: true
                        - $geometry: point
                        - not: { kind: [park, national_park, "park or protected land",conservation, protected_area, nature_reserve, airport, aerodrome, university, college] }
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [5,6,7], area: { min: 5000000000 } }
                        - { $zoom: [8],     area: { min: 1600000000 } }
                        - { $zoom: [9],     area: { min: 400000000 } }
                        - { $zoom: [10],    area: { min: 100000000 } }
                        - { $zoom: [11],    area: { min: 25000000 } }
                        - { $zoom: [12],    area: { min: 5000000 } }
                        - { $zoom: [13],    area: { min: 1000000 } }
                        - { $zoom: [14],    area: { min: 100000 } }
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [15],    area: { min: 5000 } }
                        - { $zoom: [16],    area: { min: 2000 } }
                        - { $zoom: { min: 17 } }
                draw:
                    text:
                        visible: *text_visible_poi_landuse
                        interactive: true
                        font:
                            fill: *text_fill
                            size: 12px
                            stroke: { color: *text_stroke, width: 4 }
                    icons:
                        sprite: function() { return feature.kind; }
                        sprite_default: generic
                        visible: *icon_visible_poi_landuse
                        interactive: true
                building-like:
                    filter: { kind: [commercial,residential,warehouse,public,dormitory], osm_relation: false }
                    draw:
                        icons:
                            sprite: building
                residential-relations-paris-wtf:
                    filter: { kind: [residential], osm_relation: true }
                    draw:
                        icons:
                            text: { visible: true, text_source: short_name, font: { fill: red } }
                            icons: { visible: false }
                hide-till-later:
                    filter: { kind: [pedestrian,common,railway,ship,houseboat,common,grass,wetland,pitch], $zoom: { max: 17 } }
                    draw:
                        text: { visible: false }
                        icons: { visible: false }
                only-text-later:
                    filter: { kind: [pedestrian,common,railway,ship,houseboat,common,grass,wetland,pitch], $zoom: { min: 17 } }
                    draw:
                        text: { font: { style: italic } }
                        icons: { visible: false }
```

**Comment by nvkelso** [comment]
¿Add new spreadsheet to determine "tier" of landuse feature based on kind lookup

```
kind,tier
val1,1
val2,1
val3,2
```

**Comment by nvkelso** [comment]
The sizes will be similar to how buildings.csv is setup, but you'll use some of the area thresholds from other filters.

```
  - fn: vectordatasource.transform.csv_match_properties
    resources:
      matcher:
        type: file
        init_fn: vectordatasource.transform.CSVMatcher
        path: spreadsheets/scalerank/landuse.csv
    params:
      source_layer: landuse
      target_value_type: int
```
