### ISSUE TITLE
Improve logic & perf of building drawing (server-client)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#477]
Historically we've included any building starting at zoom 13 above pixel threshold. We should still do that, but also decorate them with a new "more-or-less" style attribute that is set based on the features effective min_zoom (calculated from the area filters). Want all the buildings? Only want the biggest/tallest? Want something in between? This could allow a simple boolean evaluation client side instead of the per zoom filters, improving perf.

```
    # buildings are the only layer that gets lighting
    buildings:
        data: { source: osm, layer: buildings }
        filter: 
            any:
                # limit show smaller landuse areas to higher zooms
                - { $zoom: [13], area: { min: 100000 }, name: true }
                - { $zoom: [13], area: { min: 100000 }, kind: true }
                - { $zoom: [13], height: { min: 250 } }
                - { $zoom: [13], volume: { min: 250000 } }
                - { $zoom: [14], area: { min: 20000 }, name: true }
                - { $zoom: [14], area: { min: 20000 }, kind: true }
                - { $zoom: [14], area: { min: 5000 }, landuse_kind: true }
                - { $zoom: [14], height: { min: 150 } }
                - { $zoom: [14], volume: { min: 150000 } }
                - { $zoom: [15], area: { min: 5000 }, name: true }
                - { $zoom: [15], area: { min: 5000 }, kind: true }
                - { $zoom: [15], area: { min: 3000 }, landuse_kind: true }
                - { $zoom: [15], height: { min: 100 } }
                - { $zoom: [15], volume: { min: 100000 } }
                - { $zoom: [16], area: { min: 1000 }, name: true }
                - { $zoom: [16], area: { min: 1000 }, kind: true }
                - { $zoom: [16], area: { min: 2000 }, landuse_kind: true }
                - { $zoom: [16], volume: { min: 50000 } }
                #- { $zoom: [16], height: { min: 50 } }
                - { $zoom: { min: 17 } }
            all:
                - not: { location: underground }
#                - { $zoom: { max: 18 } }
```
