### ISSUE TITLE
zoom 9 tile has excessive landuse, other layer details

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#583]
http://vector.mapzen.com/osm/all/9/245/166.topojson?api_key=vector-tiles-HqUVidw

There are many tiny landuse features included in this tile. 

* The large ones should keep their names and independent existence. 

* The smaller ones should loose their names and be merged (like what we started doing in the roads layer in v0.7).

**Comment by nvkelso** [comment]
Download: [9:245:166.topojson.json.zip](https://github.com/mapzen/vector-datasource/files/164276/9.245.166.topojson.json.zip)

**Comment by nvkelso** [comment]
Separate tile previewed in QGIS:

![screen shot 2016-03-28 at 13 31 07](https://cloud.githubusercontent.com/assets/853051/14089385/7980494c-f4e9-11e5-9e06-ba2640385967.png)

[22.json.zip](https://github.com/mapzen/vector-datasource/files/192431/22.json.zip)

For instance, all the Urban Area polygons from Natural Earth at the same min_zoom and sort_key could be merged.

**Comment by nvkelso** [comment]
I suspect the `roads` and `boundary` layers need additional geom simplifying. 

We could also strip some properties off the boundary layer at low zooms (like `name` and the name variants) at zooms less than 8 as the zoom isn't large enough to provide screen space to do the labeling.

![screen shot 2016-03-28 at 13 35 53](https://cloud.githubusercontent.com/assets/853051/14089500/04a88642-f4ea-11e5-8c8c-ede2258343d3.png)

![screen shot 2016-03-28 at 13 35 24](https://cloud.githubusercontent.com/assets/853051/14089488/fa3fa9d8-f4e9-11e5-989a-7f199ab53d3d.png)

**Comment by zerebubuth** [comment]
Tracking changes for the linework in `roads` and `boundaries` layers in #641 - no need to conflate that task, which is about altering a threshold for a feature we already have, and this one which is about adding an entirely new feature.

**Comment by nvkelso** [comment]
**Establish some scale ranks for landuse**

From queries.yaml, these are already applied, but the CSV is empty now.

The sizes will be similar to how buildings.csv is setup, but you'll use some of the area thresholds from other filters. 

```
  - fn: vectordatasource.transform.csv_match_properties
    resources:
      matcher:
        type: file
        init_fn: vectordatasource.transform.CSVMatcher
        path: spreadsheets/scalerank/landuse.csv
    params:
      source_layer: landuse
      target_value_type: int
```
