### ISSUE TITLE
Remove unstyled OSM place locality data from most zooms

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#982]
Sister issue to #981 for Remove unstyled NE places data (preferring existing OSM data):

Here's the scene file logic pulled out of Bubble Wrap, for all zooms (mix of `name` always being true, different rules depending on `population` value being present, and sometimes also `kind_detail: [city,town]`):

```
populated-places-osm-z8:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: true
            - kind: locality
            #- kind_detail: [city,town]  # not sure why this isn't specified in src
            - $zoom: [8]

populated-places-osm-z9:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: true
            - kind: locality
            #- kind_detail: [city,town]  # not sure why this isn't specified in src
            - $zoom: [9]

populated-places-osm-z9-no-population:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: false
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [9]

populated-places-osm-z10:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: true
            - kind: locality
            #- kind_detail: [city,town]  #not sure why this is commented out in src
            - $zoom: [10]

populated-places-osm-z10-no-population:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: false
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [10]

populated-places-osm-z11:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: true
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [11]

populated-places-osm-z11-no-population:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: false
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [11]

populated-places-osm-z12:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: true
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [12]

populated-places-osm-z12-no-population:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: false
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [12]

populated-places-osm-z13-z14:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: true
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [13, 14]

populated-places-osm-z13-z14-no-population:
    filter:
        all:
            - source: [openstreetmap, openstreetmap.org]
            - name: true
            - population: false
            - kind: locality
            - kind_detail: [city,town]
            - $zoom: [13, 14]
```
