### ISSUE TITLE
George Washington National Forest should not be a national park

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#987]
[George Washington National Forest](http://www.openstreetmap.org/way/34416231) currently comes through with [`kind: national_park`](https://github.com/tilezen/vector-datasource/blob/57aeb9cd139c699840940ea8aa96f4b92db92788/integration-test/473-landuse-scalerank.py#L25), but [shouldn't](https://github.com/tilezen/vector-datasource/pull/980#issuecomment-242004509).

Relevant tags on the object:

* `boundary=national_park`
* `landuse=forest`
* `leisure=nature_reserve`
* `operator=US Forest Service`

Do we want some combination of these to override the [choice of `kind: national_park`](https://github.com/tilezen/vector-datasource/blob/57aeb9cd139c699840940ea8aa96f4b92db92788/yaml/landuse.yaml#L5-L7)?

**Comment by nvkelso** [comment]
Good catch! Browsing around the USA this seems fairly common and probably the root cause of a lot of our cludgy filter shims. 

If we see the operator is `United States Forest Service` (we normalize a list of values into that in post-processing) it should be `kind:forest` instead of `kind:national_park`. 

I've had good success in the scene file also paring with **protect_class` (to insist that a national_park can't be operated by USFS and it should generally be in only 2, 3, and 5 protect_class :

```
            national_park:
                filter:
                    all:
                        - kind: [national_park, battlefield, protected_area]
                    any:
                        - not: { operator: [ "United States Forest Service" ] }
                        - protect_class: ['2','3','5']
```

- Example [Stanislaus National Forest](http://www.openstreetmap.org/relation/972008) in California near Yosemite. 
- Stanislaus happened to have protect_class = 6, which is how we end up drawing national forests in the scene file. But this other [Humboldt](http://www.openstreetmap.org/relation/2389847) forest in Nevada has protect_class 5 so that's not guaranteed. 

I suspect these might address edge cases, while the dominant case is the example above.

-  `landuse=forest` I think this isn't worth pursing at this time as I've only found [one case](http://www.openstreetmap.org/relation/5579230) which is already addressed by the other logic, and I suspect this may do some harm unless further researched and it's an edge case so skip.

- `leisure=nature_reserve` in [Smith River](http://www.openstreetmap.org/relation/6213964) is already taken care of by operator. And counter example is [Mojave National Preserve](http://www.openstreetmap.org/relation/175098) which is operated by United States National Park Service so we don't want it to become a forest.  [Point Reyes](http://www.openstreetmap.org/relation/1250137) is also `leisure=nature_reserve` but without an operator but with a protect_class of 2.

- `leisure=park` in [San Luis Reservoir State Recreational Area](http://www.openstreetmap.org/relation/3004556) has `boundary=national_park` and `leisure=park` and 
`park:type=state_recreational_area` and no protect_class. This shouldn't be a kind national_park, just a park!

- Example [forest in Colorado](http://www.openstreetmap.org/relation/396026) that only gets demoted because of protect_class as operator is missing.

**Comment by nvkelso** [comment]
* `leisure=nature_reserve` in [North Farallon Islands State Marine Reserve](https://www.openstreetmap.org/way/436801947) has `boundary=protected_area` with `protect_class=4` in tile [11/323/791](http://vector.mapzen.com/osm/all/11/323/791.topojson). It's `operator=California Department of Fish & Wildlife` so we'd just want this to be **`kind:park`**.
* `leisure=nature_reserve` in [Mount Tamalpais Watershed](https://www.openstreetmap.org/way/297463477) has `boundary=national_park` with `boundary:type=protected_area` and `operator=Marin Municipal Water District` and `protect_class=4`. It should just be **`kind:park`**.
* `leisure=common`  in [Blithedale Summit Open Space Preserve](https://www.openstreetmap.org/way/297452972) with `boundary=national_park` and `boundary:type=protected_area` and `protect_class=5` and `operator=Marin County Parks` should just be **`kind:park`**.

**Comment by nvkelso** [comment]
**nature-reserve-boundaries**

Looking at the OSM CartoCSS files, it looks like the special outline coloring on osm.org is being driven on:

- https://github.com/gravitystorm/openstreetmap-carto/blob/0c70682a69c91b833399c1dd74409eee79ce4af1/admin.mss#L192-L223
- https://github.com/gravitystorm/openstreetmap-carto/blob/0c70682a69c91b833399c1dd74409eee79ce4af1/admin.mss#L192-L223

Snippet from "nature-reserve-boundaries" MML:

`SELECT\n    way,\n    name,\n    boundary,\n    way_area/NULLIF(!pixel_width!::real*!pixel_height!::real,0) AS way_pixels\n  FROM planet_osm_polygon\n  WHERE (boundary = 'national_park' OR leisure = 'nature_reserve')\n    AND building IS NULL\n    AND way_area > 0.01*!pixel_width!::real*!pixel_height!::real\n) AS national_park_boundaries`

(Is `boundary=protected_area` ever drawn in the default OSM.org map? There are [10s of thousands](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area) of protected_area features in OSM, so I think we _should_ keep including them in Tilezen.)

Some OSM wiki page definitions:

- [boundary](http://wiki.openstreetmap.org/wiki/Key:boundary) value
- [boundary=national_park](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dnational_park) 
- [boundary=protected_area](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area)
- [leisure=nature_reserve](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dnature_reserve)

Here's what we do now:

[landuse.jinja2#L82](https://github.com/tilezen/vector-datasource/blob/master/queries/landuse.jinja2#L82):

```
  AND (tags->'boundary' IN ('national_park', 'protected_area') OR tags->'leisure'='nature_reserve')
```

[landuse.yaml#L5-L13](https://github.com/tilezen/vector-datasource/blob/master/yaml/landuse.yaml#L5-L13)

I think the order should be more like:

- national_park with US National Park Service
- forest that are protect_class 6 or operator US National Forest Service
- common
- nature_reserve
- park
- other national_park
- protected_area
- other forest

And what we have now:

```
  - filter: {boundary: national_park}
    min_zoom: zoom + 2
    output: {kind: national_park}
  - filter: {boundary: protected_area}
    min_zoom: zoom + 2
    output: {kind: protected_area}
  - filter: {leisure: nature_reserve}
    min_zoom: zoom + 2
    output: {kind: nature_reserve}
  - filter:
      any:
        leisure: park
        landuse: park
    min_zoom: GREATEST(LEAST(zoom, 16), 9)
    output: {kind: park}
  - filter: {leisure: common}
    min_zoom: GREATEST(LEAST(zoom, 16), 9)
    output: {kind: common}
  - filter: 
      landuse: forest
      protect_class: '6'
    min_zoom: GREATEST(LEAST(zoom, 14), 7)
    output: {kind: forest}
  - filter: {landuse: forest}
    min_zoom: GREATEST(LEAST(zoom, 14), 9)
    output: {kind: forest}
```

**theme parks and zoos**

Similarly the reason why theme parks and zoos get an outline treatment is:

- https://github.com/gravitystorm/openstreetmap-carto/blob/ef48cd7448ff3b139e717f161bccddd164c47665/project.yaml#L1452-L1468
- https://github.com/gravitystorm/openstreetmap-carto/blob/778cb4889f67fe611f0be76fe4e7888a654d188f/landcover.mss#L679-L704

Snippet from "tourism-boundary" in MML:

`(SELECT\n    way,\n    way_area/NULLIF(!pixel_width!::real*!pixel_height!::real,0) AS way_pixels,\n    name,\n    tourism\n  FROM planet_osm_polygon\n  WHERE tourism = 'theme_park'\n    OR tourism = 'zoo'\n) AS tourism_boundary`

I don't think we need any special handling for `kind:theme_park` or `kind:zoo` because they are straight forward (same as their original features).
